name: base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - conda-build
  - matplotlib
  - numpy
  - pytorch
  - python-dotenv
  - jupyter
  - torchvision
  - scikit-learn
  - flake8
  - black
  - isort
  - mypy
