name: ci

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/mlops_w5

          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envs/mlops_w5

          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\mlops_w5

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-version: latest
            activate-environment: mlops_w5

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: conda env update -n mlops_w5 -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run tests
        shell: bash -l {0}
        run: pytest ./tests
